#!/bin/node

const { Repo } = require('hologit');
const TOML = require('@iarna/toml');
const fs = require('mz/fs');
const path = require('path');
const glob = require('mz-modules/glob');
const execa = require('execa');


outputResult(lensTree(process.argv[2]));

async function lensTree(treeHash) {

    // load env/input
    const repo = await Repo.getFromEnvironment();
    const git = await repo.getGit();
    const tree = await repo.createTreeFromRef(treeHash);
    const requiresTree = await tree.getChild('composer-requires');


    // init output
    const outputTree = repo.createTree();


    // check env/input
    if (!requiresTree) {
        return outputTree;
    }

    if (!requiresTree.isTree) {
        throw new Error('./composer-requires must be a tree');
    }


    // extract definitions from tree
    const composerRequire = {};
    const requiresChildren = await requiresTree.getBlobMap();
    const childPathRe = /^(?<vendor>[^/]+)\/(?<project>[^.]+).toml$/;

    for (const childPath in requiresChildren) {
        const childPathMatch = childPathRe.exec(childPath);
        if (!childPathMatch) {
            console.error(`${childPath} does not match <vendor>/<project>.toml`);
            continue;
        }

        const { vendor, project } = childPathMatch.groups;

        let parsed;
        try {
            parsed = TOML.parse(await requiresChildren[childPath].read());
        } catch (err) {
            throw new Error(`could not parse ${childPath}: ${err.message}`);
        }

        const spec = parsed['composer-requires'];
        if (!spec) {
            throw new Error(`${childPath} does not contain [composer-requires] table`);
        }

        if (!spec.vendor) {
            spec.vendor = vendor;
        }

        if (!spec.project) {
            spec.project = project;
        }

        composerRequire[`${spec.vendor}/${spec.project}`] = spec.version;
    }


    // delete anything on disk and not in index
    console.error('Cleaning working tree');
    await git.clean({ d: true, force: true });


    // generate composer manifest
    console.error('Generating composer.json');
    await fs.writeFile('composer.json', Buffer.from(JSON.stringify({ require: composerRequire })));


    // use composer to resolve and install dependencies
    console.error('Running composer install');
    let composerExitCode;
    try {
        const composerProcess = execa('composer', [
            'install',
            // '--no-autoloader',
            '--no-interaction',
            '--no-progress',
            '--no-scripts',
            '--no-dev',
            '--no-suggest',
            // '--prefer-source',
            '--classmap-authoritative'
        ], {
            env: {
                COMPOSER_ALLOW_SUPERUSER: true
            }
        });
        composerProcess.stderr.pipe(process.stderr);
        composerProcess.stdout.pipe(process.stderr);
        ({ exitCode: composerExitCode } = await composerProcess);
    } catch (err) {
        console.error(`Composer install failed: ${err.message}`);
        process.exit(1);
    }

    if (composerExitCode !== 0) {
        console.error(`composer install failed with code ${composerExitCode}`);
        process.exit(exitCode);
    }


    // capture entire vendor directory
    console.error('Populating php-bootstraps/composer-requires/');
    await git.add({ force: true }, 'vendor');
    const vendorTreeHash = await git.writeTree({ prefix: 'vendor' });
    const vendorTree = await repo.createTreeFromRef(vendorTreeHash);
    await outputTree.writeChild('php-bootstraps/composer-requires', vendorTree);


    // write PHP bootstraps script for composer-requires
    console.error('Generating php-bootstraps/composer-requires.php');
    const loaderBlob = await repo.writeBlob("<?php\nrequire_once __DIR__.'/composer-requires/autoload.php';");
    await outputTree.writeChild(`php-bootstraps/composer-requires.php`, loaderBlob);


    return outputTree;
}


async function outputResult(result) {
    result = await result;

    if (result.isTree) {
        console.log(await result.write());
        process.exit(0);
        return;
    }

    console.error('no result');
    process.exit(1);
}



// To merge with another (base?) composor.json file, use a format like this:
// {
//     "require": {
//         "wikimedia/composer-merge-plugin": "dev-master"
//     },
//     "extra": {
//         "merge-plugin": {
//             "include": [
//                 "composer.local.json",
//                 "extensions/*/composer.json"
//             ],
//             "require": [
//                 "submodule/composer.json"
//             ],
//             "recurse": true,
//             "replace": false,
//             "ignore-duplicates": false,
//             "merge-dev": true,
//             "merge-extra": false,
//             "merge-extra-deep": false,
//             "merge-scripts": false
//         }
//     }
// }